/**
 * Helpers for two-pass encode generated by codegen.
 * These are low-level primitives that the generated sizeOf/encodeTo use directly.
 */

export { varint32Size, varint64Size } from './varint.js'
export { zigzagEncode32 } from './zigzag.js'

const B = typeof globalThis.Buffer === 'function' ? globalThis.Buffer : null
const te = B ? null : new TextEncoder()

/** Calculate UTF-8 byte length of a string. */
export function strByteLen(s: string): number {
    return B ? B.byteLength(s, 'utf8') : te!.encode(s).length
}

/** Write UTF-8 string directly into buffer at offset. */
export function strWrite(s: string, buf: Uint8Array, pos: number, len: number): void {
    if (B) {
        ;(buf as unknown as { utf8Write(s: string, o: number, l: number): number }).utf8Write(
            s,
            pos,
            len
        )
    } else {
        te!.encodeInto(s, buf.subarray(pos))
    }
}

/** Write a varint32 into buffer at pos. Returns new pos. */
export function writeVarint(value: number, buf: Uint8Array, p: number): number {
    value = value >>> 0
    if (value < 0x80) {
        buf[p++] = value
        return p
    }
    buf[p++] = (value & 0x7f) | 0x80
    if (value < 0x4000) {
        buf[p++] = value >>> 7
        return p
    }
    buf[p++] = ((value >>> 7) & 0x7f) | 0x80
    if (value < 0x200000) {
        buf[p++] = value >>> 14
        return p
    }
    buf[p++] = ((value >>> 14) & 0x7f) | 0x80
    if (value < 0x10000000) {
        buf[p++] = value >>> 21
        return p
    }
    buf[p++] = ((value >>> 21) & 0x7f) | 0x80
    buf[p++] = value >>> 28
    return p
}

/**
 * Allocate a buffer for encoding.
 */
export function allocBuf(n: number): Uint8Array {
    return B ? B.allocUnsafe(n) : new Uint8Array(n)
}

/**
 * Finalize a buffer allocated by allocBuf.
 */
export function finalizeBuf(buf: Uint8Array, size: number): Uint8Array {
    void size
    return buf
}

// Shared scratch for double writing
const f64Arr = new Float64Array(1)
const f64Bytes = new Uint8Array(f64Arr.buffer)
const f32Arr = new Float32Array(1)
const f32Bytes = new Uint8Array(f32Arr.buffer)

/** Write a double (8 bytes LE) into buf at pos. Returns pos + 8. */
export function writeDouble(value: number, buf: Uint8Array, p: number): number {
    f64Arr[0] = value
    buf[p++] = f64Bytes[0]!
    buf[p++] = f64Bytes[1]!
    buf[p++] = f64Bytes[2]!
    buf[p++] = f64Bytes[3]!
    buf[p++] = f64Bytes[4]!
    buf[p++] = f64Bytes[5]!
    buf[p++] = f64Bytes[6]!
    buf[p++] = f64Bytes[7]!
    return p
}

/** Write a float (4 bytes LE) into buf at pos. Returns pos + 4. */
export function writeFloat(value: number, buf: Uint8Array, p: number): number {
    f32Arr[0] = value
    buf[p++] = f32Bytes[0]!
    buf[p++] = f32Bytes[1]!
    buf[p++] = f32Bytes[2]!
    buf[p++] = f32Bytes[3]!
    return p
}

/** Write a fixed32 (4 bytes LE) into buf at pos. Returns pos + 4. */
export function writeFixed32(value: number, buf: Uint8Array, p: number): number {
    const v = value >>> 0
    buf[p++] = v & 0xff
    buf[p++] = (v >>> 8) & 0xff
    buf[p++] = (v >>> 16) & 0xff
    buf[p++] = (v >>> 24) & 0xff
    return p
}

/** Write a fixed64 (8 bytes LE) from lo/hi into buf at pos. Returns pos + 8. */
export function writeFixed64(lo: number, hi: number, buf: Uint8Array, p: number): number {
    buf[p++] = lo & 0xff
    buf[p++] = (lo >>> 8) & 0xff
    buf[p++] = (lo >>> 16) & 0xff
    buf[p++] = (lo >>> 24) & 0xff
    buf[p++] = hi & 0xff
    buf[p++] = (hi >>> 8) & 0xff
    buf[p++] = (hi >>> 16) & 0xff
    buf[p++] = (hi >>> 24) & 0xff
    return p
}

/** Write a bool (1 byte) into buf at pos. Returns pos + 1. */
export function writeBool(value: boolean, buf: Uint8Array, p: number): number {
    buf[p++] = value ? 1 : 0
    return p
}

/** Write an int32 as varint (negative values use 10-byte sign-extended encoding). Returns new pos. */
export function writeInt32(value: number, buf: Uint8Array, p: number): number {
    if (value >= 0) return writeVarint(value, buf, p)
    // Negative int32 is sign-extended to 10 bytes
    buf[p++] = (value & 0x7f) | 0x80
    buf[p++] = ((value >>> 7) & 0x7f) | 0x80
    buf[p++] = ((value >>> 14) & 0x7f) | 0x80
    buf[p++] = ((value >>> 21) & 0x7f) | 0x80
    buf[p++] = ((value >>> 28) & 0x0f) | 0x70 | 0x80
    buf[p++] = 0xff
    buf[p++] = 0xff
    buf[p++] = 0xff
    buf[p++] = 0xff
    buf[p++] = 0x01
    return p
}

/** Calculate the byte length of an int32 encoded as varint. */
export function int32Size(value: number): number {
    if (value >= 0) {
        value = value >>> 0
        if (value < 0x80) return 1
        if (value < 0x4000) return 2
        if (value < 0x200000) return 3
        if (value < 0x10000000) return 4
        return 5
    }
    return 10 // negative int32 is always 10 bytes
}

/** Write a varint64 (lo, hi pair) into buf at pos. Returns new pos. */
export function writeVarint64(lo: number, hi: number, buf: Uint8Array, p: number): number {
    if (hi === 0) {
        lo = lo >>> 0
        if (lo < 0x80) {
            buf[p++] = lo
            return p
        }
        buf[p++] = (lo & 0x7f) | 0x80
        if (lo < 0x4000) {
            buf[p++] = lo >>> 7
            return p
        }
        buf[p++] = ((lo >>> 7) & 0x7f) | 0x80
        if (lo < 0x200000) {
            buf[p++] = lo >>> 14
            return p
        }
        buf[p++] = ((lo >>> 14) & 0x7f) | 0x80
        if (lo < 0x10000000) {
            buf[p++] = lo >>> 21
            return p
        }
        buf[p++] = ((lo >>> 21) & 0x7f) | 0x80
        buf[p++] = lo >>> 28
        return p
    }
    while (hi > 0 || lo > 127) {
        buf[p++] = (lo & 0x7f) | 0x80
        lo = ((lo >>> 7) | (hi << 25)) >>> 0
        hi = hi >>> 7
    }
    buf[p++] = lo
    return p
}

/** Write a sint32 (zigzag encoded) into buf at pos. Returns new pos. */
export function writeSint32(value: number, buf: Uint8Array, p: number): number {
    return writeVarint(((value << 1) ^ (value >> 31)) >>> 0, buf, p)
}

/**
 * Copy bytes from src into buf at pos. Returns pos + src.length.
 * Uses manual byte copy for small/medium buffers to avoid FastBuffer allocation
 * that V8 triggers when calling TypedArray.set() with a Buffer argument.
 */
export function writeBytes(src: Uint8Array, buf: Uint8Array, p: number): number {
    const len = src.length
    if (len <= 64) {
        // Manual copy avoids FastBuffer wrapper creation from buf.set(Buffer, offset)
        let i = 0
        for (; i + 7 < len; i += 8) {
            buf[p + i] = src[i]!
            buf[p + i + 1] = src[i + 1]!
            buf[p + i + 2] = src[i + 2]!
            buf[p + i + 3] = src[i + 3]!
            buf[p + i + 4] = src[i + 4]!
            buf[p + i + 5] = src[i + 5]!
            buf[p + i + 6] = src[i + 6]!
            buf[p + i + 7] = src[i + 7]!
        }
        for (; i < len; i++) buf[p + i] = src[i]!
    } else {
        buf.set(src, p)
    }
    return p + len
}
