/**
 * JavaScript + .d.ts file generator.
 * Generates .js with JSDoc type annotations and a corresponding .d.ts file.
 */

import type { ProtoFile, TsGeneratorOptions } from './ts-generator.js'
import { generateTypeScript } from './ts-generator.js'

const GENERATED_HEADER = '// Generated by protobuf-x. DO NOT EDIT.'

export interface JsGeneratorResult {
    /** The JavaScript file content. */
    js: string
    /** The TypeScript declaration file content. */
    dts: string
}

/**
 * Generate JavaScript + .d.ts output from a parsed proto file.
 *
 * Strategy: Generate the TypeScript first, then transform it.
 * The .d.ts is the TypeScript source with implementations replaced by declarations.
 * The .js is the TypeScript source with type annotations stripped.
 */
export function generateJavaScript(
    proto: ProtoFile,
    options?: TsGeneratorOptions
): JsGeneratorResult {
    const tsSource = generateTypeScript(proto, options)

    return {
        js: tsToJs(tsSource),
        dts: tsToDts(tsSource)
    }
}

/**
 * Get the output file paths for .js + .d.ts.
 */
export function getJsOutputPaths(protoPath: string): { js: string; dts: string } {
    const base = protoPath.replace(/\.proto$/, '_pb')
    return {
        js: `${base}.js`,
        dts: `${base}.d.ts`
    }
}

/**
 * Strip TypeScript type annotations from source to produce valid JavaScript.
 * This transform is intentionally scoped to the patterns emitted by generateTypeScript.
 */
function tsToJs(tsSource: string): string {
    const lines = tsSource.split('\n')
    const result: string[] = []
    let braceDepth = 0
    let skipInterfaceDepth: number | null = null
    let skipTypeAlias = false
    let currentEnum: {
        indent: string
        name: string
        members: Array<{ name: string; value: string }>
    } | null = null
    // When inside `export namespace X { ... }`, convert `export const Y = Z;` to `X.Y = Z;`
    // and strip `export type Y = ...;` lines. The namespace block itself is erased.
    let currentNamespace: { name: string; depth: number } | null = null

    for (const line of lines) {
        const trimmed = line.trim()
        const openBraces = countChar(line, '{')
        const closeBraces = countChar(line, '}')

        if (currentEnum !== null) {
            if (trimmed === '}') {
                result.push(
                    `${currentEnum.indent}export const ${currentEnum.name} = /*#__PURE__*/Object.freeze({`
                )
                for (const member of currentEnum.members) {
                    result.push(`${currentEnum.indent}    ${member.name}: ${member.value},`)
                }
                result.push(`${currentEnum.indent}});`)
                currentEnum = null
            } else {
                const memberMatch = trimmed.match(/^([A-Za-z_$][\w$]*)\s*=\s*([^,]+),?$/)
                if (memberMatch) {
                    currentEnum.members.push({
                        name: memberMatch[1]!,
                        value: memberMatch[2]!.trim()
                    })
                }
            }
            continue
        }

        if (skipInterfaceDepth !== null) {
            braceDepth += openBraces - closeBraces
            if (braceDepth <= skipInterfaceDepth) {
                skipInterfaceDepth = null
            }
            continue
        }

        if (skipTypeAlias) {
            if (trimmed === '' || (!trimmed.startsWith('|') && !trimmed.startsWith('&'))) {
                skipTypeAlias = false
            } else {
                continue
            }
        }

        if (trimmed.startsWith('import type ')) {
            continue
        }

        // Enter namespace block: `export namespace Foo {`
        if (currentNamespace === null) {
            const nsMatch = line.match(/^(\s*)export namespace (\w+)\s*\{$/)
            if (nsMatch) {
                currentNamespace = { name: nsMatch[2]!, depth: braceDepth }
                braceDepth += 1
                continue
            }
        } else {
            // Inside namespace: handle close, type aliases, and const/import assignments
            if (trimmed === '}' && braceDepth === currentNamespace.depth + 1) {
                braceDepth -= 1
                currentNamespace = null
                continue
            }
            // Drop `export type ...` lines entirely
            if (trimmed.startsWith('export type ')) {
                continue
            }
            // Convert `export import X = Y;` to `NsName.X = Y;`. The TS-only
            // `export import` form re-exports a merged value+type+namespace
            // symbol; in JS we only need the runtime value reference, which
            // is the same as the const assignment.
            const importMatch = trimmed.match(/^export import (\w+)\s*=\s*([^;]+);$/)
            if (importMatch) {
                result.push(`${currentNamespace.name}.${importMatch[1]!} = ${importMatch[2]!};`)
                continue
            }
            // Convert `export const X = Y;` to `NsName.X = Y;`
            const constMatch = trimmed.match(/^export const (\w+)\s*=\s*([^;]+);$/)
            if (constMatch) {
                result.push(`${currentNamespace.name}.${constMatch[1]!} = ${constMatch[2]!};`)
                continue
            }
            // Skip any other content inside namespace (shouldn't happen in codegen output)
            continue
        }

        const enumMatch = line.match(/^(\s*)export const enum (\w+) \{$/)
        if (enumMatch) {
            currentEnum = {
                indent: enumMatch[1]!,
                name: enumMatch[2]!,
                members: []
            }
            continue
        }

        if (trimmed.startsWith('export interface ') && trimmed.endsWith('{')) {
            skipInterfaceDepth = braceDepth
            braceDepth += openBraces - closeBraces
            continue
        }

        if (trimmed.startsWith('export type ')) {
            skipTypeAlias = !trimmed.endsWith(';')
            continue
        }

        let transformed = line
            .replace(/extends ([A-Za-z_$][\w$]*)<[^>]+>/g, 'extends $1')
            // Strip TS-only `implements IFoo[, IBar]` clause from class declarations
            .replace(
                /^(\s*export class [A-Za-z_$][\w$]*(?:\s+extends\s+[A-Za-z_$][\w$.]*)?)\s+implements\s+[A-Za-z_$][\w$.]*(?:\s*,\s*[A-Za-z_$][\w$.]*)*\s*\{/,
                '$1 {'
            )
            .replace(
                /^(\s*)static readonly descriptor:\s*MessageDescriptor\s*=\s*\{$/,
                '$1static descriptor = {'
            )
            .replace(
                /^(\s*)export const (\w+Descriptor):\s*ServiceDescriptor\s*=\s*\{$/,
                '$1export const $2 = {'
            )
            .replace(
                /^(\s*)export const (\w+):\s*[A-Za-z_$][\w$.]*(?:<[^>]+>)?\s*=\s*\{$/,
                '$1export const $2 = {'
            )
            .replace(/constructor\(init\?\s*:\s*Partial<[^>]+>\)\s*\{/, 'constructor(init) {')
            .replace(
                /static encode\(msg:\s*[^,]+,\s*w\?\s*:\s*BinaryWriter\):\s*BinaryWriter\s*\{/,
                'static encode(msg, w) {'
            )
            .replace(
                /static decode\(input:\s*Uint8Array(?:\s*\|\s*BinaryReader)?(?:,\s*length\?\s*:\s*number)?\):\s*[\w$.]+\s*\{/,
                'static decode(input, length) {'
            )
            .replace(
                /static decodeFrom\(r:\s*BinaryReader,\s*end:\s*number\):\s*[\w$.]+\s*\{/,
                'static decodeFrom(r, end) {'
            )
            .replace(/static sizeOf\(msg:\s*[^)]+\):\s*number\s*\{/, 'static sizeOf(msg) {')
            .replace(
                /static encodeTo\(msg:\s*[^,]+,\s*buf:\s*Uint8Array,\s*p:\s*number\):\s*number\s*\{/,
                'static encodeTo(msg, buf, p) {'
            )
            .replace(/toBinary\(\):\s*Uint8Array\s*\{/, 'toBinary() {')
            .replace(/static toJSON\(msg:\s*[^)]+\)(?::\s*[\w$.]+)?\s*\{/, 'static toJSON(msg) {')
            .replace(
                /static fromJSON\(json:\s*[\w$.]+\)(?::\s*[\w$.]+)?\s*\{/,
                'static fromJSON(json) {'
            )
            .replace(
                /static verify\(msg:\s*[^)]+\)(?::\s*string\s*\|\s*null)?\s*\{/,
                'static verify(msg) {'
            )
            // Strip type annotations from local const/let/var declarations
            .replace(
                /^(\s*(?:const|let|var)\s+\w+):\s*[A-Za-z_$][\w$.]*(?:<[^>]*>)?(?:\[\])?\s*=/gm,
                '$1 ='
            )
            // Strip type annotations with union types (e.g. `let x: string | undefined = ...`)
            .replace(
                /^(\s*(?:const|let|var)\s+\w+):\s*[A-Za-z_$][\w$.]*(?:\s*\|\s*[A-Za-z_$][\w$.]*)+\s*=/gm,
                '$1 ='
            )
            // Strip type assertion in `for...in` loop header: `for (const x in obj as Type)` → `for (const x in obj)`
            .replace(/\bin\s+this\s+as\s+[A-Za-z_$][\w$.]*(?:<[^>]*>)?/g, 'in this')
            // Strip `(this as any)` and `(msg as any)` parenthesized casts
            .replace(/\(this as any\)/g, 'this')
            .replace(/\(msg as any\)/g, 'msg')
            // Strip return type annotations from arrow functions and methods
            .replace(
                /^(\s*(?:static\s+)?(?:async\s+)?(?:\*\s*)?[A-Za-z_$][\w$]*\s*\([^)]*\)):\s*[A-Za-z_$][\w$.]*(?:<[^>]*>)?(?:\[\])?\s*\{/gm,
                '$1 {'
            )
        if (!trimmed.startsWith('import {')) {
            transformed = transformed
                .replace(/\s+as\s+const\b/g, '')
                .replace(/\s+as\s+[A-Za-z_$][\w$.]*(?:<[^>]+>)?(?:\[\])?/g, '')
        }

        if (!trimmed.startsWith('default:')) {
            const fieldWithInitializer = transformed.match(
                /^(\s*)([A-Za-z_$][\w$]*)(\?)?:\s*(.+?)\s*=\s*(.+);$/
            )
            if (fieldWithInitializer) {
                transformed = `${fieldWithInitializer[1]!}${fieldWithInitializer[2]!} = ${fieldWithInitializer[5]!};`
            } else {
                const fieldWithoutInitializer = transformed.match(
                    /^(\s*)([A-Za-z_$][\w$]*)(\?)?:\s*([^;]+);$/
                )
                if (fieldWithoutInitializer) {
                    // Keep optional/undefined-only fields out of emitted JS to avoid
                    // eagerly stamping hundreds of `undefined` properties in constructors.
                    transformed = ''
                }
            }
        }

        if (transformed !== '') {
            result.push(transformed)
        }
        braceDepth += openBraces - closeBraces
    }

    return squashBlankLines(result).join('\n').trimEnd() + '\n'
}

/**
 * Transform TypeScript source into a .d.ts declaration file.
 * Replaces implementations with declarations while preserving public types.
 */
function tsToDts(tsSource: string): string {
    const lines = tsSource.split('\n')
    const result: string[] = []
    let braceDepth = 0
    let skipBodyDepth: number | null = null
    // Track when we're inside a `export namespace ... { }` block. In ambient
    // .d.ts context, `export const X = Y` initializers must be literals, so we
    // collapse the const+type alias pair into a single `export import X = Y`
    // which works for both classes and const enums.
    let inNamespaceDepth: number | null = null

    for (const line of lines) {
        const trimmed = line.trim()
        const openBraces = (line.match(/\{/g) || []).length
        const closeBraces = (line.match(/\}/g) || []).length

        if (skipBodyDepth !== null) {
            braceDepth += openBraces - closeBraces
            if (braceDepth <= skipBodyDepth) {
                skipBodyDepth = null
            }
            continue
        }

        // Inside a namespace block: rewrite `export const X = Y;` (illegal in
        // ambient context with non-literal initializer) to `export const X: typeof Y;`.
        // The companion `export type X = Y;` line is preserved as-is. Together they
        // form a class+namespace merge that works for both classes and const enums.
        if (inNamespaceDepth !== null) {
            // Closing brace of the namespace
            if (trimmed === '}' && braceDepth === inNamespaceDepth + 1) {
                result.push(line)
                braceDepth -= 1
                inNamespaceDepth = null
                continue
            }
            const constMatch = trimmed.match(/^export const (\w+)\s*=\s*([^;]+);$/)
            if (constMatch) {
                const [, name, target] = constMatch
                const indent = line.slice(0, line.indexOf('export'))
                result.push(`${indent}export const ${name!}: typeof ${target!};`)
                continue
            }
            // `export type X = Y;` is fine in ambient context — pass through
            // Other content passes through too
            result.push(line)
            braceDepth += openBraces - closeBraces
            continue
        }

        // Enter namespace block
        const nsMatch = trimmed.match(/^export namespace (\w+)\s*\{$/)
        if (nsMatch) {
            result.push(line)
            inNamespaceDepth = braceDepth
            braceDepth += 1
            continue
        }

        if (trimmed === GENERATED_HEADER) {
            result.push(GENERATED_HEADER)
            result.push('// Type declarations.')
            continue
        }

        // Strip runtime implementation helpers from imports — only keep type-relevant symbols
        if (trimmed.startsWith('import {') && !trimmed.startsWith('import type')) {
            const dtsOnlyImports = [
                'Message',
                'BinaryReader',
                'BinaryWriter',
                'FieldRule',
                'ScalarType'
            ]
            const importMatch = line.match(/^(import \{)([^}]+)(\} from .+)$/)
            if (importMatch) {
                const symbols = importMatch[2]!
                    .split(',')
                    .map((s) => s.trim())
                    .filter((s) => {
                        const base = s.split(/\s+as\s+/)[0]?.trim() ?? s
                        return dtsOnlyImports.includes(base)
                    })
                if (symbols.length > 0) {
                    result.push(`${importMatch[1]!} ${symbols.join(', ')} ${importMatch[3]!}`)
                }
                continue
            }
        }

        if (trimmed.startsWith('const _fd_') || trimmed.startsWith('const _ext_')) {
            continue
        }

        if (trimmed.startsWith('Object.assign(')) {
            continue
        }

        if (trimmed === 'static readonly descriptor: MessageDescriptor = {') {
            const declLine = line.replace(/\s*=\s*\{$/, ';')
            result.push(declLine)
            skipBodyDepth = braceDepth
            braceDepth += openBraces - closeBraces
            continue
        }

        if (trimmed.startsWith('export const ') && trimmed.endsWith('= {')) {
            const declLine = line
                .replace(/\s*=\s*\{$/, ';')
                .replace('export const ', 'export declare const ')
            result.push(declLine)
            skipBodyDepth = braceDepth
            braceDepth += openBraces - closeBraces
            continue
        }

        if (
            (trimmed.startsWith('static encode(') ||
                trimmed.startsWith('static decode(') ||
                trimmed.startsWith('static decodeFrom(') ||
                trimmed.startsWith('static sizeOf(') ||
                trimmed.startsWith('static encodeTo(') ||
                trimmed.startsWith('static toJSON(') ||
                trimmed.startsWith('static fromJSON(') ||
                trimmed.startsWith('static verify(') ||
                trimmed.startsWith('toBinary(') ||
                trimmed.startsWith('constructor(')) &&
            trimmed.endsWith('{')
        ) {
            result.push(line.replace(/\s*\{$/, ';'))
            skipBodyDepth = braceDepth
            braceDepth += openBraces - closeBraces
            continue
        }

        if (trimmed.startsWith('export class ')) {
            result.push(line.replace('export class ', 'export declare class '))
        } else if (trimmed.startsWith('export const enum ')) {
            result.push(line.replace('export const enum ', 'export declare const enum '))
        } else {
            const fieldWithInitializer = line.match(
                /^(\s*)([A-Za-z_$][\w$]*)(\??):\s*(.+?)\s*=\s*.+;$/
            )
            if (fieldWithInitializer) {
                result.push(
                    `${fieldWithInitializer[1]!}${fieldWithInitializer[2]!}${fieldWithInitializer[3]!}: ${fieldWithInitializer[4]!};`
                )
            } else {
                result.push(line)
            }
        }

        braceDepth += openBraces - closeBraces
    }

    if (result.length === 0 || result[0] !== GENERATED_HEADER) {
        result.unshift('// Type declarations.')
        result.unshift(GENERATED_HEADER)
    }

    return compactStaticDecls(squashBlankLines(result)).join('\n').trimEnd() + '\n'
}

/** Remove blank lines between consecutive static method/field declarations in .d.ts */
function compactStaticDecls(lines: string[]): string[] {
    const out: string[] = []
    for (let i = 0; i < lines.length; i++) {
        const line = lines[i]!
        const isBlank = line.trim() === ''
        if (isBlank && i > 0 && i + 1 < lines.length) {
            const prev = lines[i - 1]!.trim()
            const next = lines[i + 1]!.trim()
            const isStaticOrMethod = (s: string) =>
                s.startsWith('static ') || s.startsWith('toBinary(') || s.startsWith('constructor(')
            if (isStaticOrMethod(prev) && isStaticOrMethod(next)) continue
        }
        out.push(line)
    }
    return out
}

function countChar(line: string, char: string): number {
    let count = 0
    for (const current of line) {
        if (current === char) {
            count++
        }
    }
    return count
}

function squashBlankLines(lines: string[]): string[] {
    const squashed: string[] = []
    let previousBlank = false

    for (const line of lines) {
        const isBlank = line.trim() === ''
        if (isBlank && previousBlank) {
            continue
        }
        squashed.push(line)
        previousBlank = isBlank
    }

    return squashed
}
